<a href="https://colab.research.google.com/github/parthpurwar/CP-/blob/main/mlbegin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install ydata-profiling

In [1]:
import pandas as pd
df = pd.read_csv('/content/synthetic_fooddelivery_dataset.csv', encoding = 'latin1')

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df

,ID_Pesanan,Waktu_Transaksi,Kategori_Menu,Harga_Pesanan,Jarak_Kirim_KM,Waktu_Tunggu_Menit,Rating_Pelanggan,Ulasan_Teks,Status_Promo,Tingkat_Keluhan,Status_Pesanan
0,ORD-2024-000001,2024-03-22 13:15:14,Kopi,9000,NaN,27,4.0,Sesuai pesanan,False,Tidak Ada,Selesai
1,ORD-2024-000002,2024-01-14 17:05:37,Mie,21000,3.742238,37,NaN,NaN,False,Tidak Ada,Selesai
2,ORD-2024-000003,2024-01-04 12:32:38,Martabak,33500,12.677149,49,NaN,NaN,True,Rendah,Selesai
3,ORD-2024-000004,2024-01-26 22:34:26,Kopi,13500,2.338085,20,5.0,Mantap gan!,False,Tidak Ada,Selesai
4,ORD-2024-000005,2024-03-16 11:48:51,Ayam,47500,0.949764,27,4.0,Top bgt kualitasnya,True,Rendah,Selesai
...,...,...,...,...,...,...,...,...,...,...,...
8495,ORD-2024-008496,24/03/2024 15:58,Mie,29500,1.492591,28,5.0,Puas bgt,False,Tidak Ada,Selesai
8496,ORD-2024-008497,09/03/2024 20:56,Mie,24000,0.500000,25,NaN,NaN,True,Tidak Ada,Selesai
8497,ORD-2024-008498,2024-01-08 20:00:27,Kopi,19000,3.674235,42,3.0,OK,False,Tinggi,Dibatalkan
8498,ORD-2024-008499,2024-03-10 13:15:54,Ayam,61000,1.032143,9,NaN,NaN,False,Tidak Ada,Selesai


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(dfz.drop('vendor_survived', axis=1),
                                                    df2['vendor_survived'],
                                                    test_size = 0.3,
                                                    random_state=0)

##Standard Scaler

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(x_train)

x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)


In [ ]:
scaler.mean_

array([2425.59925637,   37.11169284])

In [ ]:
x_train_scaled = pd.DataFrame(x_train_scaled, columns=x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled, columns=x_test.columns)

In [ ]:
x_train_scaled

,avg_daily_revenue_inr,vendor_age_years
0,-0.486476,-0.773736
1,-0.349801,-0.106039
2,-0.292660,0.466273
3,-0.369622,0.275502
4,NaN,-0.487580
...,...,...
15395,-0.153378,1.610897
15396,-0.240918,NaN
15397,0.004678,-0.296810
15398,8.467837,-1.346048


In [ ]:
df2.describe()

,avg_daily_revenue_inr,vendor_age_years,vendor_survived
count,20062.000000,21242.000000,22000.000000
mean,2391.236096,37.172630,0.425636
std,4034.506720,10.513603,0.494450
min,185.410000,20.000000,0.000000
25%,981.422500,28.000000,0.000000
50%,1516.590000,37.000000,0.000000
75%,2390.127500,46.000000,1.000000
max,39997.330000,75.000000,1.000000


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

scaler.fit(x_train)

x_train_mnmx_scaled= scaler.transform(x_train)
x_test_mnmx_scaled = scaler.transform(x_test)

In [ ]:
x_train_mnmx_scaled = pd.DataFrame(x_train_mnmx_scaled, columns = x_train.columns)
x_test_mnmx_scaled = pd.DataFrame(x_test_mnmx_scaled, columns = x_test.columns)

#Encoding Categorical Data

In [34]:
data = pd.read_csv('/content/student_exam_performance_dataset.csv')
data

,student_id,gender,age,parental_education,family_income,internet_access,study_environment,study_hours_per_day,attendance_rate,sleep_hours,...,online_courses_completed,tutoring,math_score,reading_score,writing_score,science_score,final_exam_score,previous_gpa,pass_fail,grade_category
0,S00001,Male,17,High School,Medium,Yes,Quiet,2.98,96.5,6.05,...,1,Yes,42.8,62.4,54.8,51.8,49.1,2.44,Fail,F
1,S00002,Female,18,High School,Low,Yes,Quiet,4.45,95.7,6.96,...,0,Yes,77.9,73.5,64.4,61.6,70.1,2.79,Pass,C
2,S00003,Male,17,High School,Medium,No,Quiet,3.75,76.0,7.02,...,4,Yes,53.5,38.3,36.3,47.1,42.2,1.49,Fail,F
3,S00004,Male,18,Bachelor,Medium,Yes,Quiet,2.03,72.6,6.23,...,4,No,28.3,23.5,32.0,39.0,31.9,1.34,Fail,F
4,S00005,Male,18,Bachelor,Medium,Yes,Quiet,5.14,87.3,8.54,...,0,No,74.7,54.9,73.6,55.5,66.4,2.60,Pass,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,S09996,Female,15,Master,High,Yes,Moderate,3.80,83.1,7.48,...,1,No,44.2,38.2,38.5,39.0,41.9,1.54,Fail,F
9996,S09997,Male,15,High School,Medium,Yes,Quiet,2.46,68.0,6.76,...,3,No,56.8,46.2,50.6,34.9,47.5,1.49,Fail,F
9997,S09998,Female,15,High School,Low,Yes,Moderate,5.08,76.0,6.90,...,2,No,67.4,50.5,63.7,83.3,64.2,2.38,Pass,D
9998,S09999,Female,18,Bachelor,Medium,Yes,Moderate,1.56,91.0,7.13,...,1,No,35.4,35.5,46.8,47.2,44.3,1.45,Fail,F


In [35]:
data = data[['age','family_income','study_hours_per_day','final_exam_score','grade_category','pass_fail']]
data

,age,family_income,study_hours_per_day,final_exam_score,grade_category,pass_fail
0,17,Medium,2.98,49.1,F,Fail
1,18,Low,4.45,70.1,C,Pass
2,17,Medium,3.75,42.2,F,Fail
3,18,Medium,2.03,31.9,F,Fail
4,18,Medium,5.14,66.4,C,Pass
...,...,...,...,...,...,...
9995,15,High,3.80,41.9,F,Fail
9996,15,Medium,2.46,47.5,F,Fail
9997,15,Low,5.08,64.2,D,Pass
9998,18,Medium,1.56,44.3,F,Fail


In [36]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data.drop('pass_fail', axis=1),
                                                    data['pass_fail'],
                                                    test_size = 0.3,
                                                    random_state=0)

In [58]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop = 'first',dtype=np.int32)

In [59]:
x_train_new = ohe.fit_transform(x_train[['grade_category']]).toarray()
x_train_new


array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       ...,
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0]], dtype=int32)

In [60]:
x_test_new = ohe.fit_transform(x_test[['grade_category']]).toarray()
x_test_new


array([[0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       ...,
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1]], dtype=int32)

In [61]:
np.hstack((x_train[['age','family_income','study_hours_per_day','final_exam_score']].values, x_train_new)).shape

(7000, 8)

##Column Transformer

In [62]:
from sklearn.Compose import ColumnTransformer

ModuleNotFoundError: No module named 'sklearn.Compose'

In [63]:
transformer = ColumnTransformer(transformers = [
    ('tnf1', SimpleImputer(), ['']),
    ('tnf2', OrdinalEncoder(categories = [['','']]),['']),
    ('tnf3', OneHotEncoder(sparse= False, drop = 'first'),[''])
], remaining = 'passthrough')

NameError: name 'ColumnTransformer' is not defined

In [ ]:
tansformer

Scikit Learn Pipelines
